version: 2

sources:
  - name: blockchain
    database: crypto
    schema: raw
    config:
      freshness:
        warn_after: {count: 1, period: day}
      loaded_at_field: block_timestamp
    tables:
      - name: transactions

  - name: binance
    database: crypto
    schema: raw
    config:
      freshness:
        warn_after: {count: 1, period: day}
      loaded_at_field: open_time
    tables:
      - name: binance_btcusdt_1d